name: Publish

on:
  release:
    types: [published]

jobs:
  publish-npm:
    name: "Publish to npm"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm run build
      - run: npm run test
        env:
          TEST_RVVUP_API_KEY: ${{ secrets.TEST_RVVUP_API_KEY }}

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
